// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `json:"name"`
	Email string `json:"email"`
	DOB string `json:"dob"`
	Mobile string `json:"mobile"`
}

type Response struct {
	Message string `json:"message"`
}
